### ISSUE TITLE
Encoder crashes when changing recipe type

### ISSUE THREAD

**Issue by LoneStarrr** [TheLMiffy1111/PackagedAuto#32]
Version: 1.16.5-2.0.0.3 (in modpack Chroma2 1.1.0)

How to reproduce:

- Place encoder
- Open encoder
- Click the recipe type button
- Once you hit the basic crafting type, it will crash with the log below. It does persist the recipe type change after logging back in (on a multiplayer server)

Relevant crash log section:
``
[03Sep2021 20:38:52.114] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.NullPointerException: null
	at thelm.packagedauto.util.MiscHelper.getRecipeManager(MiscHelper.java:330) ~[packagedauto:2.0.0.3]
	at thelm.packagedauto.recipe.CraftingPackageRecipeInfo.generateFromStacks(CraftingPackageRecipeInfo.java:118) ~[packagedauto:2.0.0.3]
	at thelm.packagedauto.inventory.EncoderPatternItemHandler.updateRecipeInfo(EncoderPatternItemHandler.java:71) ~[packagedauto:2.0.0.3]
	at thelm.packagedauto.inventory.EncoderPatternItemHandler.read(EncoderPatternItemHandler.java:42) ~[packagedauto:2.0.0.3]
	at thelm.packagedauto.tile.EncoderTile.readSync(EncoderTile.java:52) ~[packagedauto:2.0.0.3]
	at thelm.packagedauto.tile.BaseTile.onDataPacket(BaseTile.java:103) ~[packagedauto:2.0.0.3]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147273_a(ClientPlayNetHandler.java:1145) ~[?:?]
	at net.minecraft.network.play.server.SUpdateTileEntityPacket.func_148833_a(SourceFile:55) ~[?:?]
	at net.minecraft.network.play.server.SUpdateTileEntityPacket.func_148833_a(SourceFile:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[03Sep2021 20:38:53.929] [Render thread/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Unknown custom packet identifier: servertabinfo:network
[03Sep2021 20:38:53.929] [Render thread/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Unknown custom packet identifier: servertabinfo:network
``

**Comment by LoneStarrr** [comment]
I created a PR for this issue: https://github.com/TheLMiffy1111/PackagedAuto/pull/33
