### ISSUE TITLE
PackagedAuto's blocks do not like being moved by either Carry On or Mekanism's Cardboard Box

### ISSUE THREAD

**Issue by TrashboxBobylev** [TheLMiffy1111/PackagedAuto#54]
```
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Loading data after part of a grid, this is invalid.
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1817)
    at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalStateException: Loading data after part of a grid, this is invalid.
    at appeng.me.GridNode.loadFromNBT(GridNode.java:272)
    at thelm.packagedauto.integration.appeng.networking.HostHelperTile.readFromNBT(HostHelperTile.java:52)
    at thelm.packagedauto.tile.TilePackager.readFromNBT(TilePackager.java:430)
    at mekanism.common.block.BlockCardboardBox.onBlockActivated(BlockCardboardBox.java:86)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more
```

This happens with Packagers, Unpackagers and all Package Crafters. I found the same issue with ME Fluid Auto Filler and ME Fluid Assembler from AE Additions, everything else from AE2 is transfered with Carry On/Cardboard Box gracefully.

**Comment by TheLMiffy1111** [comment]
Should be fixed in 1.0.15.56
