### ISSUE TITLE
`NullPointerException` on `ItemPackage.getPatternForItem`

### ISSUE THREAD

**Issue by SettingDust** [TheLMiffy1111/PackagedAuto#59]
Looks like the result of `getPatternType` is null https://github.com/TheLMiffy1111/PackagedAuto/blob/1.12/src/main/java/thelm/packagedauto/item/ItemPackage.java#L124
```
[19:14:35] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at thelm.packagedauto.item.ItemPackage.getPatternForItem(ItemPackage.java:124) ~[ItemPackage.class:1.0.15.56]
	at appeng.helpers.DualityInterface.addToCraftingList(DualityInterface.java:549) ~[DualityInterface.class:?]
	at appeng.helpers.DualityInterface.updateCraftingList(DualityInterface.java:454) ~[DualityInterface.class:?]
	at appeng.helpers.DualityInterface.initialize(DualityInterface.java:1477) ~[DualityInterface.class:?]
	at appeng.tile.misc.TileInterface.onReady(TileInterface.java:150) ~[TileInterface.class:?]
	at appeng.hooks.TickHandler.onTick(TickHandler.java:190) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1061_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-090a6ffb]
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67) ~[%5B延迟监视%5D%20LagGoggles-1.12.2-5.9-140.jar:1.12.2-5.9-140]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) ~[EventBus.class:git-CatServer-1.12.2-090a6ffb]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:268) ~[FMLCommonHandler.class:git-CatServer-1.12.2-090a6ffb]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:884) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_345]
```

**Comment by TheLMiffy1111** [comment]
should be fixed in 1.0.15.57
